### ISSUE TITLE
No Publisher for "/map_image/full/compressed" topic

### ISSUE THREAD

**Issue by sumitkuml** [husarion/route_admin_panel#2]
I can't find any publisher for "/map_image/full/compressed" topic and hence there is no data on this topic. I tried to subscribe to "/map_image/full" topic instead as there is data available here but still not getting any map in frontend. Can you please tell me which node is expected to publish data on  "/map_image/full/compressed" topic?

**Comment by lukaszmitka** [comment]
Publisher of `compressed` topic is part of `image_transport` plugin. This is handled internally by plugin,as long as there is published `/map_image/full` also `/map_image/full/compressed` should be published.
Do you have `image_transport` installed?
What is output of: `rosrun image_transport list_transports`?

**Comment by sumitkuml** [comment]
Following is the output of rosrun image_transport list_transports

Declared transports:
image_transport/raw

Details:
----------
"image_transport/raw"
 - Provided by package: image_transport
 - Publisher: 
      This is the default publisher. It publishes the Image as-is on the base topic.
    
 - Subscriber: 
      This is the default pass-through subscriber for topics of type sensor_msgs/Image.

**Comment by lukaszmitka** [comment]
Your system is missing `image_transport_compressed` plugin, install it with:
`sudo apt install ros-kinetic-image-transport-plugins`

**Comment by sumitkuml** [comment]
Could not install plugin. Getting following error -

Err:1 http://packages.ros.org/ros/ubuntu xenial/main amd64 ros-kinetic-compressed-depth-image-transport amd64 1.9.5-0xenial-20190320-180918-0800
  404  Not Found [IP: 64.50.233.100 80]
Err:2 http://packages.ros.org/ros/ubuntu xenial/main amd64 ros-kinetic-compressed-image-transport amd64 1.9.5-0xenial-20190320-180934-0800
  404  Not Found [IP: 64.50.233.100 80]
Err:3 http://packages.ros.org/ros/ubuntu xenial/main amd64 ros-kinetic-theora-image-transport amd64 1.9.5-0xenial-20190320-144041-0800
  404  Not Found [IP: 64.50.233.100 80]
Err:4 http://packages.ros.org/ros/ubuntu xenial/main amd64 ros-kinetic-image-transport-plugins amd64 1.9.5-0xenial-20190320-193554-0800
  404  Not Found [IP: 64.50.233.100 80]
E: Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/r/ros-kinetic-compressed-depth-image-transport/ros-kinetic-compressed-depth-image-transport_1.9.5-0xenial-20190320-180918-0800_amd64.deb  404  Not Found [IP: 64.50.233.100 80]

E: Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/r/ros-kinetic-compressed-image-transport/ros-kinetic-compressed-image-transport_1.9.5-0xenial-20190320-180934-0800_amd64.deb  404  Not Found [IP: 64.50.233.100 80]

E: Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/r/ros-kinetic-theora-image-transport/ros-kinetic-theora-image-transport_1.9.5-0xenial-20190320-144041-0800_amd64.deb  404  Not Found [IP: 64.50.233.100 80]

E: Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/r/ros-kinetic-image-transport-plugins/ros-kinetic-image-transport-plugins_1.9.5-0xenial-20190320-193554-0800_amd64.deb  404  Not Found [IP: 64.50.233.100 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by lukaszmitka** [comment]
Do `sudo apt update` before installing.

**Comment by sumitkuml** [comment]
Thanks a lot...Everything is perfect now!
